//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int ProductId { get; set; }
        public string IsBooked { get; set; }
        public string IsSaved { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<int> NoOfAvailableRooms { get; set; }
        public Nullable<int> RoomPrice { get; set; }
    }
}
